### ISSUE TITLE
would you like to take a look at our api?

### ISSUE THREAD

**Issue by Stockard** [DataHerb/dataherb-python#3]
I come across this repo and found it very similar to our API, though much more mature. 
https://github.com/Glacier-Ice/data-sci-api

we have problems in creating a standard of dataset collection and API documentation for end-users

is there a way we can collaborate?

**Comment by emptymalei** [comment]
It kind of depends on the focus. If the focus is on data science, the DataHerb approach works fine for such small datasets. If you need a complicated interactive front-end, providing data files won't help that much.

We will see how things goes on both sides.

**Comment by Stockard** [comment]
As our focus is on data science too, I think the difference is mainly about function.
DataHerb works really well with relative static datasets, while data-sci-api is more elastic thus requires further development.

I believe DataHerb shows a very clear logic of presenting the document for datasets sharing. That's why I have strong interested in it.

**Comment by emptymalei** [comment]
> I believe DataHerb shows a very clear logic of presenting the document for datasets sharing. That's why I have strong interested in it.

This is quite easy. We can also build this for `Glacier-Ice/data-sci-api`.

**Comment by emptymalei** [comment]
@Stockard I believe using a database is a much better option for a stable API. A database is more *type-safe* than plaintext tabular data format. 

However, there is aso a solution to this problem using the DataHerb approach. We could save data files as parquet and host them on GitHub. We apply a simple lambda function to create an API. This will make sure we have kinda type-safe data and a dynamic API. With multiple lambda functions and parquet files, we will build a microservice structure. 
And this will be a cheaper and more flexible solution than the current `Glacier-Ice/data-sci-api` mono app structure.

But each approach has its own pros and cons. For Glacier-Ice, I believe either frameworks works fine.
